language: python
install:
  - pip install tox
  - python setup.py install_egg_info
script:
  - tox
matrix:
  include:
      env: TOXENV=py36-3.0.X
    - python: 3.7
      env: TOXENV=py37-3.0.X
      dist: xenial
    - python: 3.8
      env: TOXENV=py38-3.0.X
      dist: xenial

notifications:
  irc: "irc.freenode.org#django-compressor"
after_success:
  - pip install codecov
  - codecov
